version: '3.4'

services:
  conference-pg-db:
    image: postgres:13
    container_name: conference-pg-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: conference
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgresql-data:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"
    networks:
      - net

  conference-service:
    build: conference-service
    container_name: conference-service
    restart: unless-stopped
    depends_on:
      - conference-pg-db
    ports:
      - "8080:8080"
    networks:
      - net

volumes:
  postgresql-data:

networks:
  net:
